const path = require('path');
const ejs = require('ejs');
const art = require('art-template');
const htmlMinifier = require('html-minifier');

module.exports = {
    compiler: {

        engine: {
            // 'art-template': art,
            ejs,
        },

        root: path.resolve(__dirname, '../../resources/views'),

        options: {
            useHtmlMinifier: process.env.NODE_ENV === 'production' ? htmlMinifier : '',
            htmlMinifierOptions: {
                collapseWhitespace: true,
                conservativeCollapse: true,
                collapseBooleanAttributes: true,
                removeEmptyAttributes: true,
                decodeEntities: true,
                includeAutoGeneratedTags: false,
                removeOptionalTags: true,
                removeAttributeQuotes: true,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                minifyCSS: true,
                minifyJS: true,
            },
        },

        defaultContext: {
            env: process.env.NODE_ENV || 'production',
        },

        includeViewExtension: true,

        viewExt: 'html',
    },
};